package alpha_vantage.enums;

import org.springframework.beans.factory.annotation.Value;

/**
 * Enums taken from the Alpha Vantage API Documentation Market List:
 * https://www.alphavantage.co/digital_currency_list/
 */
public enum DigitalCurrency {
    //    2GIVE("GiveCoin"), // Need to figure out how to use
    ADT("adToken"),
    AGI("SingularityNET"),
    AION("Aion"),
    AMBER("AmberCoin"),
    ANT("Aragon"),
    ARK("Ark"),
    ATB("ATBCoin"),
    ATM("ATMChain"),
    AVT("Aventus"),
    B3("B3Coin"),
    BAT("Basic-Attention-Token"),
    BAY("BitBay"),
    BCD("Bitcoin-Diamond"),
    BCH("Bitcoin-Cash"),
    BITB("BitBean"),
    BNB("Binance-Coin"),
    BNT("Bancor-Network-Token"),
    BQ("bitqy"),
    BTC("Bitcoin"),
    BTG("Bitcoin-Gold"),
    BTS("BitShares"),
    BTX("Bitcore"),
    BURST("Burstcoin"),
    BUZZ("BuzzCoin"),
    CANN("CannabisCoin"),
    CCRB("CryptoCarbon"),
    CFI("Cofound-it"),
    CLOAK("CloakCoin"),
    CTR("Centra"),
    CVC("Civic"),
    DASH("Dash"),
    DATA("DATAcoin"),
    DOGE("DogeCoin"),
    EDG("Edgeless"),
    EDO("Eidoo"),
    ELF("aelf"),
    EMB("Embercoin"),
    EMC("Emercoin"),
    EOS("EOS"),
    EOT("EOT-Token"),
    ETC("Ethereum-Classic"),
    ETH("Ethereum"),
    ETHOS("Ethos"),
    ETP("Metaverse-Entropy"),
    ETT("EncryptoTel"),
    FRST("FirstCoin"),
    FUN("FunFair"),
    GAME("GameCredits"),
    GAS("Gas"),
    GCR("GCRCoin"),
    GNO("Gnosis-Token"),
    HMQ("Humaniq"),
    HVN("Hive"),
    ICN("ICONOMI"),
    IFT("investFeed"),
    INK("Ink"),
    IOST("IOStoken"),
    IOTA("IOTA"),
    IXC("iXcoin"),
    KICK("KickCoin"),
    LINDA("Linda"),
    LKK("Lykke"),
    LRC("Loopring"),
    LSK("Lisk"),
    LTC("Litecoin"),
    MANA("Decentraland"),
    MAX("Maxcoin"),
    MCAP("MCAP"),
    MCO("Monaco"),
    MNX("MinexCoin"),
    MTN("MedToken"),
    NDC("NeverDie-Coin"),
    NEO("NEO"),
    NLC2("NoLimitCoin"),
    NMC("Namecoin"),
    OBITS("Obits"),
    ODN("Obsidian"),
    OMG("OmiseGo"),
    PAY("TenX"),
    PING("CryptoPing"),
    PIVX("PIVX"),
    PLBT("Polybius"),
    POSW("PoSW-Coin"),
    QASH("QASH"),
    QAU("Quantum"),
    QTUM("Qtum"),
    R("Revain"),
    RBIES("Rubies"),
    RCN("Ripio-Credit-Network"),
    RDD("ReddCoin"),
    RDN("Raiden-Network-Token"),
    REC("Regalcoin"),
    REP("Augur"),
    REQ("Request-Network"),
    RISE("Rise"),
    RLC("RLC-Token"),
    RLT("RouletteToken"),
    RRT("Recovery-Right-Tokens"),
    SAN("Santiment-Network-Token"),
    SBTC("Super-Bitcoin"),
    SHIFT("SHIFT"),
    SIGT("Signatum"),
    SNC("SunContract"),
    SNGLS("SingularDTV"),
    SNM("SONM"),
    SNT("Status-Network-Token"),
    SPANK("SpankChain"),
    START("Startcoin"),
    TAAS("Taas"),
    TIME("Time"),
    TKN("TokenCard"),
    TNB("Time-New-Bank"),
    TNT("Tierion"),
    TOA("ToaCoin"),
    TRC("Terracoin"),
    TRST("Trustcoin"),
    TRX("Tronix"),
    UNO("Unobtanium"),
    URO("Uro"),
    USDT("Tether"),
    VEN("VeChain"),
    VIA("Viacoin"),
    VPN("VPNCoin"),
    VRS("Veros"),
    VTC("Vertcoin"),
    WAVES("Waves"),
    WAX("Wax-Token"),
    WGO("WavesGo"),
    WGR("Wagerr"),
    XBY("XtraBYtes"),
    XEM("NEM"),
    XLM("Stellar"),
    XMR("Monero"),
    XVG("Verge"),
    XZC("ZCoin"),
    YOYOW("YOYOW"),
    ZEC("Zcash"),
    ZET("Zetacoin"),
    ZRX("0x");

    private String fullName;

    public String getFullName() {
        return fullName;
    }

    public void setFullName(String fullName) {
        this.fullName = fullName;
    }

    DigitalCurrency(String fullName) {
        this.fullName = fullName;
    }
}
